// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/msf/register_proxy.proto

package msf

type DiscussList struct {
	DiscussCode *uint64 `protobuf:"varint,1,opt"`
	DiscussSeq  *uint64 `protobuf:"varint,2,opt"`
	MemberSeq   *uint64 `protobuf:"varint,3,opt"`
	InfoSeq     *uint64 `protobuf:"varint,4,opt"`
	BHotGroup   *bool   `protobuf:"varint,5,opt"`
	RedpackTime *uint64 `protobuf:"varint,6,opt"`
	HasMsg      *bool   `protobuf:"varint,7,opt"`
	DicussFlag  *int64  `protobuf:"varint,8,opt"`
}

func (x *DiscussList) GetDiscussCode() uint64 {
	if x != nil && x.DiscussCode != nil {
		return *x.DiscussCode
	}
	return 0
}

func (x *DiscussList) GetDiscussSeq() uint64 {
	if x != nil && x.DiscussSeq != nil {
		return *x.DiscussSeq
	}
	return 0
}

func (x *DiscussList) GetMemberSeq() uint64 {
	if x != nil && x.MemberSeq != nil {
		return *x.MemberSeq
	}
	return 0
}

func (x *DiscussList) GetInfoSeq() uint64 {
	if x != nil && x.InfoSeq != nil {
		return *x.InfoSeq
	}
	return 0
}

func (x *DiscussList) GetBHotGroup() bool {
	if x != nil && x.BHotGroup != nil {
		return *x.BHotGroup
	}
	return false
}

func (x *DiscussList) GetRedpackTime() uint64 {
	if x != nil && x.RedpackTime != nil {
		return *x.RedpackTime
	}
	return 0
}

func (x *DiscussList) GetHasMsg() bool {
	if x != nil && x.HasMsg != nil {
		return *x.HasMsg
	}
	return false
}

func (x *DiscussList) GetDicussFlag() int64 {
	if x != nil && x.DicussFlag != nil {
		return *x.DicussFlag
	}
	return 0
}

type GroupList struct {
	GroupCode             *uint64 `protobuf:"varint,1,opt"`
	GroupSeq              *uint64 `protobuf:"varint,2,opt"`
	MemberSeq             *uint64 `protobuf:"varint,3,opt"`
	Mask                  *uint64 `protobuf:"varint,4,opt"`
	RedpackTime           *uint64 `protobuf:"varint,5,opt"`
	HasMsg                *bool   `protobuf:"varint,6,opt"`
	GroupFlag             *int64  `protobuf:"varint,7,opt"`
	GroupType             *uint64 `protobuf:"varint,8,opt"`
	GroupNameSeq          *uint32 `protobuf:"varint,9,opt"`
	GroupMemberSeq        *uint32 `protobuf:"varint,10,opt"`
	UinFlagEx2            *uint32 `protobuf:"varint,11,opt"`
	ImportantMsgLatestSeq *uint32 `protobuf:"varint,12,opt"`
}

func (x *GroupList) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *GroupList) GetGroupSeq() uint64 {
	if x != nil && x.GroupSeq != nil {
		return *x.GroupSeq
	}
	return 0
}

func (x *GroupList) GetMemberSeq() uint64 {
	if x != nil && x.MemberSeq != nil {
		return *x.MemberSeq
	}
	return 0
}

func (x *GroupList) GetMask() uint64 {
	if x != nil && x.Mask != nil {
		return *x.Mask
	}
	return 0
}

func (x *GroupList) GetRedpackTime() uint64 {
	if x != nil && x.RedpackTime != nil {
		return *x.RedpackTime
	}
	return 0
}

func (x *GroupList) GetHasMsg() bool {
	if x != nil && x.HasMsg != nil {
		return *x.HasMsg
	}
	return false
}

func (x *GroupList) GetGroupFlag() int64 {
	if x != nil && x.GroupFlag != nil {
		return *x.GroupFlag
	}
	return 0
}

func (x *GroupList) GetGroupType() uint64 {
	if x != nil && x.GroupType != nil {
		return *x.GroupType
	}
	return 0
}

func (x *GroupList) GetGroupNameSeq() uint32 {
	if x != nil && x.GroupNameSeq != nil {
		return *x.GroupNameSeq
	}
	return 0
}

func (x *GroupList) GetGroupMemberSeq() uint32 {
	if x != nil && x.GroupMemberSeq != nil {
		return *x.GroupMemberSeq
	}
	return 0
}

func (x *GroupList) GetUinFlagEx2() uint32 {
	if x != nil && x.UinFlagEx2 != nil {
		return *x.UinFlagEx2
	}
	return 0
}

func (x *GroupList) GetImportantMsgLatestSeq() uint32 {
	if x != nil && x.ImportantMsgLatestSeq != nil {
		return *x.ImportantMsgLatestSeq
	}
	return 0
}

type SvcPbResponsePullDisMsgProxy struct {
	MemberSeq *uint64 `protobuf:"varint,1,opt"`
	Content   []byte  `protobuf:"bytes,2,opt"`
}

func (x *SvcPbResponsePullDisMsgProxy) GetMemberSeq() uint64 {
	if x != nil && x.MemberSeq != nil {
		return *x.MemberSeq
	}
	return 0
}

type SvcRegisterProxyMsgResp struct {
	Result          *uint32                           `protobuf:"varint,1,opt"`
	ErrMsg          []byte                            `protobuf:"bytes,2,opt"`
	Flag            *uint32                           `protobuf:"varint,3,opt"`
	Seq             *uint32                           `protobuf:"varint,4,opt"`
	Info            *SvcResponseMsgInfo               `protobuf:"bytes,5,opt"`
	GroupList       []*GroupList                      `protobuf:"bytes,6,rep"`
	DiscussList     []*DiscussList                    `protobuf:"bytes,7,rep"`
	GroupMsg        []*SvcResponsePbPullGroupMsgProxy `protobuf:"bytes,8,rep"`
	DiscussMsg      []*SvcPbResponsePullDisMsgProxy   `protobuf:"bytes,9,rep"`
	C2CMsg          []byte                            `protobuf:"bytes,10,opt"`
	PubAccountMsg   []byte                            `protobuf:"bytes,11,opt"`
	DiscussListFlag *uint32                           `protobuf:"varint,12,opt"`
}

func (x *SvcRegisterProxyMsgResp) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SvcRegisterProxyMsgResp) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

func (x *SvcRegisterProxyMsgResp) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *SvcRegisterProxyMsgResp) GetDiscussListFlag() uint32 {
	if x != nil && x.DiscussListFlag != nil {
		return *x.DiscussListFlag
	}
	return 0
}

type SvcResponseMsgInfo struct {
	GroupNum   *uint32 `protobuf:"varint,1,opt"`
	DiscussNum *uint32 `protobuf:"varint,2,opt"`
}

func (x *SvcResponseMsgInfo) GetGroupNum() uint32 {
	if x != nil && x.GroupNum != nil {
		return *x.GroupNum
	}
	return 0
}

func (x *SvcResponseMsgInfo) GetDiscussNum() uint32 {
	if x != nil && x.DiscussNum != nil {
		return *x.DiscussNum
	}
	return 0
}

type SvcResponsePbPullGroupMsgProxy struct {
	MemberSeq *uint64 `protobuf:"varint,1,opt"`
	Content   []byte  `protobuf:"bytes,2,opt"`
}

func (x *SvcResponsePbPullGroupMsgProxy) GetMemberSeq() uint64 {
	if x != nil && x.MemberSeq != nil {
		return *x.MemberSeq
	}
	return 0
}
