// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: objmsg.proto

package msg

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MsgPic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmallPicUrl    []byte `protobuf:"bytes,1,opt,name=smallPicUrl,proto3" json:"smallPicUrl,omitempty"`
	OriginalPicUrl []byte `protobuf:"bytes,2,opt,name=originalPicUrl,proto3" json:"originalPicUrl,omitempty"`
	LocalPicId     int32  `protobuf:"varint,3,opt,name=localPicId,proto3" json:"localPicId,omitempty"`
}

func (x *MsgPic) Reset() {
	*x = MsgPic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPic) ProtoMessage() {}

func (x *MsgPic) ProtoReflect() protoreflect.Message {
	mi := &file_objmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPic.ProtoReflect.Descriptor instead.
func (*MsgPic) Descriptor() ([]byte, []int) {
	return file_objmsg_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPic) GetSmallPicUrl() []byte {
	if x != nil {
		return x.SmallPicUrl
	}
	return nil
}

func (x *MsgPic) GetOriginalPicUrl() []byte {
	if x != nil {
		return x.OriginalPicUrl
	}
	return nil
}

func (x *MsgPic) GetLocalPicId() int32 {
	if x != nil {
		return x.LocalPicId
	}
	return 0
}

type ObjMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType        int32             `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Title          []byte            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	BytesAbstact   []byte            `protobuf:"bytes,3,opt,name=bytesAbstact,proto3" json:"bytesAbstact,omitempty"`
	TitleExt       []byte            `protobuf:"bytes,5,opt,name=titleExt,proto3" json:"titleExt,omitempty"`
	MsgPic         []*MsgPic         `protobuf:"bytes,6,rep,name=msgPic,proto3" json:"msgPic,omitempty"`
	MsgContentInfo []*MsgContentInfo `protobuf:"bytes,7,rep,name=msgContentInfo,proto3" json:"msgContentInfo,omitempty"`
	ReportIdShow   int32             `protobuf:"varint,8,opt,name=reportIdShow,proto3" json:"reportIdShow,omitempty"`
}

func (x *ObjMsg) Reset() {
	*x = ObjMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjMsg) ProtoMessage() {}

func (x *ObjMsg) ProtoReflect() protoreflect.Message {
	mi := &file_objmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjMsg.ProtoReflect.Descriptor instead.
func (*ObjMsg) Descriptor() ([]byte, []int) {
	return file_objmsg_proto_rawDescGZIP(), []int{1}
}

func (x *ObjMsg) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *ObjMsg) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ObjMsg) GetBytesAbstact() []byte {
	if x != nil {
		return x.BytesAbstact
	}
	return nil
}

func (x *ObjMsg) GetTitleExt() []byte {
	if x != nil {
		return x.TitleExt
	}
	return nil
}

func (x *ObjMsg) GetMsgPic() []*MsgPic {
	if x != nil {
		return x.MsgPic
	}
	return nil
}

func (x *ObjMsg) GetMsgContentInfo() []*MsgContentInfo {
	if x != nil {
		return x.MsgContentInfo
	}
	return nil
}

func (x *ObjMsg) GetReportIdShow() int32 {
	if x != nil {
		return x.ReportIdShow
	}
	return 0
}

type MsgContentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentInfoId []byte   `protobuf:"bytes,1,opt,name=contentInfoId,proto3" json:"contentInfoId,omitempty"`
	MsgFile       *MsgFile `protobuf:"bytes,2,opt,name=msgFile,proto3" json:"msgFile,omitempty"`
}

func (x *MsgContentInfo) Reset() {
	*x = MsgContentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgContentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContentInfo) ProtoMessage() {}

func (x *MsgContentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_objmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContentInfo.ProtoReflect.Descriptor instead.
func (*MsgContentInfo) Descriptor() ([]byte, []int) {
	return file_objmsg_proto_rawDescGZIP(), []int{2}
}

func (x *MsgContentInfo) GetContentInfoId() []byte {
	if x != nil {
		return x.ContentInfoId
	}
	return nil
}

func (x *MsgContentInfo) GetMsgFile() *MsgFile {
	if x != nil {
		return x.MsgFile
	}
	return nil
}

type MsgFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusId         int32  `protobuf:"varint,1,opt,name=busId,proto3" json:"busId,omitempty"`
	FilePath      []byte `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`
	FileSize      int64  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileName      string `protobuf:"bytes,4,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Int64DeadTime int64  `protobuf:"varint,5,opt,name=int64DeadTime,proto3" json:"int64DeadTime,omitempty"`
	FileSha1      []byte `protobuf:"bytes,6,opt,name=fileSha1,proto3" json:"fileSha1,omitempty"`
	Ext           []byte `protobuf:"bytes,7,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *MsgFile) Reset() {
	*x = MsgFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFile) ProtoMessage() {}

func (x *MsgFile) ProtoReflect() protoreflect.Message {
	mi := &file_objmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFile.ProtoReflect.Descriptor instead.
func (*MsgFile) Descriptor() ([]byte, []int) {
	return file_objmsg_proto_rawDescGZIP(), []int{3}
}

func (x *MsgFile) GetBusId() int32 {
	if x != nil {
		return x.BusId
	}
	return 0
}

func (x *MsgFile) GetFilePath() []byte {
	if x != nil {
		return x.FilePath
	}
	return nil
}

func (x *MsgFile) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MsgFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MsgFile) GetInt64DeadTime() int64 {
	if x != nil {
		return x.Int64DeadTime
	}
	return 0
}

func (x *MsgFile) GetFileSha1() []byte {
	if x != nil {
		return x.FileSha1
	}
	return nil
}

func (x *MsgFile) GetExt() []byte {
	if x != nil {
		return x.Ext
	}
	return nil
}

var File_objmsg_proto protoreflect.FileDescriptor

var file_objmsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72,
	0x0a, 0x06, 0x4d, 0x73, 0x67, 0x50, 0x69, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x6d, 0x61, 0x6c,
	0x6c, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73,
	0x6d, 0x61, 0x6c, 0x6c, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x69, 0x63, 0x55,
	0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x69, 0x63, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x69, 0x63,
	0x49, 0x64, 0x22, 0xf6, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x41, 0x62, 0x73, 0x74, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x41, 0x62, 0x73, 0x74, 0x61, 0x63,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x12, 0x1f, 0x0a,
	0x06, 0x6d, 0x73, 0x67, 0x50, 0x69, 0x63, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x4d, 0x73, 0x67, 0x50, 0x69, 0x63, 0x52, 0x06, 0x6d, 0x73, 0x67, 0x50, 0x69, 0x63, 0x12, 0x37,
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x49, 0x64, 0x53, 0x68, 0x6f, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x53, 0x68, 0x6f, 0x77, 0x22, 0x5a, 0x0a, 0x0e, 0x4d,
	0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65, 0x61, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x31, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x31, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x65, 0x78,
	0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_objmsg_proto_rawDescOnce sync.Once
	file_objmsg_proto_rawDescData = file_objmsg_proto_rawDesc
)

func file_objmsg_proto_rawDescGZIP() []byte {
	file_objmsg_proto_rawDescOnce.Do(func() {
		file_objmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_objmsg_proto_rawDescData)
	})
	return file_objmsg_proto_rawDescData
}

var file_objmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_objmsg_proto_goTypes = []interface{}{
	(*MsgPic)(nil),         // 0: MsgPic
	(*ObjMsg)(nil),         // 1: ObjMsg
	(*MsgContentInfo)(nil), // 2: MsgContentInfo
	(*MsgFile)(nil),        // 3: MsgFile
}
var file_objmsg_proto_depIdxs = []int32{
	0, // 0: ObjMsg.msgPic:type_name -> MsgPic
	2, // 1: ObjMsg.msgContentInfo:type_name -> MsgContentInfo
	3, // 2: MsgContentInfo.msgFile:type_name -> MsgFile
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_objmsg_proto_init() }
func file_objmsg_proto_init() {
	if File_objmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_objmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgContentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_objmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_objmsg_proto_goTypes,
		DependencyIndexes: file_objmsg_proto_depIdxs,
		MessageInfos:      file_objmsg_proto_msgTypes,
	}.Build()
	File_objmsg_proto = out.File
	file_objmsg_proto_rawDesc = nil
	file_objmsg_proto_goTypes = nil
	file_objmsg_proto_depIdxs = nil
}
