// Code generated by Proto2Go.Net. Only used for MiraiGo. DO NOT EDIT.
// Source: oidb0x88d.proto

package oidb0x88d

import (
	"github.com/pkg/errors"
	"go.dedis.ch/protobuf"
)

type (
	GroupCardPrefix struct {
		Introduction []byte   `protobuf:"1,opt"`
		Prefix       [][]byte `protobuf:"2"`
	}

	GroupExInfoOnly struct {
		TribeId          *uint32 `protobuf:"1,opt"`
		MoneyForAddGroup *uint32 `protobuf:"2,opt"`
	}

	GroupGeoInfo struct {
		Owneruin   *uint64 `protobuf:"1,opt"`
		Settime    *uint32 `protobuf:"2,opt"`
		Cityid     *uint32 `protobuf:"3,opt"`
		Longitude  *int64  `protobuf:"4,opt"`
		Latitude   *int64  `protobuf:"5,opt"`
		Geocontent []byte  `protobuf:"6,opt"`
		PoiId      *uint64 `protobuf:"7,opt"`
	}

	GroupHeadPortrait struct {
		PicCnt           *uint32                  `protobuf:"1,opt"`
		Info             []*GroupHeadPortraitInfo `protobuf:"2"`
		DefaultId        *uint32                  `protobuf:"3,opt"`
		VerifyingPicCnt  *uint32                  `protobuf:"4,opt"`
		VerifyingpicInfo []*GroupHeadPortraitInfo `protobuf:"5"`
	}

	GroupHeadPortraitInfo struct {
		PicId  *uint32 `protobuf:"1,opt"`
		LeftX  *uint32 `protobuf:"2,opt"`
		LeftY  *uint32 `protobuf:"3,opt"`
		RightX *uint32 `protobuf:"4,opt"`
		RightY *uint32 `protobuf:"5,opt"`
	}

	GroupInfo struct {
		GroupOwner                              *uint64            `protobuf:"1,opt"`
		GroupCreateTime                         *uint32            `protobuf:"2,opt"`
		GroupFlag                               *uint32            `protobuf:"3,opt"`
		GroupFlagExt                            *uint32            `protobuf:"4,opt"`
		GroupMemberMaxNum                       *uint32            `protobuf:"5,opt"`
		GroupMemberNum                          *uint32            `protobuf:"6,opt"`
		GroupOption                             *uint32            `protobuf:"7,opt"`
		GroupClassExt                           *uint32            `protobuf:"8,opt"`
		GroupSpecialClass                       *uint32            `protobuf:"9,opt"`
		GroupLevel                              *uint32            `protobuf:"10,opt"`
		GroupFace                               *uint32            `protobuf:"11,opt"`
		GroupDefaultPage                        *uint32            `protobuf:"12,opt"`
		GroupInfoSeq                            *uint32            `protobuf:"13,opt"`
		GroupRoamingTime                        *uint32            `protobuf:"14,opt"`
		GroupName                               []byte             `protobuf:"15,opt"`
		GroupMemo                               []byte             `protobuf:"16,opt"`
		GroupFingerMemo                         []byte             `protobuf:"17,opt"`
		GroupClassText                          []byte             `protobuf:"18,opt"`
		GroupAllianceCode                       []*uint32          `protobuf:"19"`
		GroupExtraAdmNum                        *uint32            `protobuf:"20,opt"`
		GroupUin                                *uint64            `protobuf:"21,opt"`
		GroupCurMsgSeq                          *uint32            `protobuf:"22,opt"`
		GroupLastMsgTime                        *uint32            `protobuf:"23,opt"`
		GroupQuestion                           []byte             `protobuf:"24,opt"`
		GroupAnswer                             []byte             `protobuf:"25,opt"`
		GroupVisitorMaxNum                      *uint32            `protobuf:"26,opt"`
		GroupVisitorCurNum                      *uint32            `protobuf:"27,opt"`
		LevelNameSeq                            *uint32            `protobuf:"28,opt"`
		GroupAdminMaxNum                        *uint32            `protobuf:"29,opt"`
		GroupAioSkinTimestamp                   *uint32            `protobuf:"30,opt"`
		GroupBoardSkinTimestamp                 *uint32            `protobuf:"31,opt"`
		GroupAioSkinUrl                         []byte             `protobuf:"32,opt"`
		GroupBoardSkinUrl                       []byte             `protobuf:"33,opt"`
		GroupCoverSkinTimestamp                 *uint32            `protobuf:"34,opt"`
		GroupCoverSkinUrl                       []byte             `protobuf:"35,opt"`
		GroupGrade                              *uint32            `protobuf:"36,opt"`
		ActiveMemberNum                         *uint32            `protobuf:"37,opt"`
		CertificationType                       *uint32            `protobuf:"38,opt"`
		CertificationText                       []byte             `protobuf:"39,opt"`
		GroupRichFingerMemo                     []byte             `protobuf:"40,opt"`
		TagRecord                               []*TagRecord       `protobuf:"41"`
		GroupGeoInfo                            *GroupGeoInfo      `protobuf:"42,opt"`
		HeadPortraitSeq                         *uint32            `protobuf:"43,opt"`
		HeadPortrait                            *GroupHeadPortrait `protobuf:"44,opt"`
		ShutupTimestamp                         *uint32            `protobuf:"45,opt"`
		ShutupTimestampMe                       *uint32            `protobuf:"46,opt"`
		CreateSourceFlag                        *uint32            `protobuf:"47,opt"`
		CmduinMsgSeq                            *uint32            `protobuf:"48,opt"`
		CmduinJoinTime                          *uint32            `protobuf:"49,opt"`
		CmduinUinFlag                           *uint32            `protobuf:"50,opt"`
		CmduinFlagEx                            *uint32            `protobuf:"51,opt"`
		CmduinNewMobileFlag                     *uint32            `protobuf:"52,opt"`
		CmduinReadMsgSeq                        *uint32            `protobuf:"53,opt"`
		CmduinLastMsgTime                       *uint32            `protobuf:"54,opt"`
		GroupTypeFlag                           *uint32            `protobuf:"55,opt"`
		AppPrivilegeFlag                        *uint32            `protobuf:"56,opt"`
		StGroupExInfo                           *GroupExInfoOnly   `protobuf:"57,opt"`
		GroupSecLevel                           *uint32            `protobuf:"58,opt"`
		GroupSecLevelInfo                       *uint32            `protobuf:"59,opt"`
		CmduinPrivilege                         *uint32            `protobuf:"60,opt"`
		PoidInfo                                []byte             `protobuf:"61,opt"`
		CmduinFlagEx2                           *uint32            `protobuf:"62,opt"`
		ConfUin                                 *uint64            `protobuf:"63,opt"`
		ConfMaxMsgSeq                           *uint32            `protobuf:"64,opt"`
		ConfToGroupTime                         *uint32            `protobuf:"65,opt"`
		PasswordRedbagTime                      *uint32            `protobuf:"66,opt"`
		SubscriptionUin                         *uint64            `protobuf:"67,opt"`
		MemberListChangeSeq                     *uint32            `protobuf:"68,opt"`
		MembercardSeq                           *uint32            `protobuf:"69,opt"`
		RootId                                  *uint64            `protobuf:"70,opt"`
		ParentId                                *uint64            `protobuf:"71,opt"`
		TeamSeq                                 *uint32            `protobuf:"72,opt"`
		HistoryMsgBeginTime                     *uint64            `protobuf:"73,opt"`
		InviteNoAuthNumLimit                    *uint64            `protobuf:"74,opt"`
		CmduinHistoryMsgSeq                     *uint32            `protobuf:"75,opt"`
		CmduinJoinMsgSeq                        *uint32            `protobuf:"76,opt"`
		GroupFlagext3                           *uint32            `protobuf:"77,opt"`
		GroupOpenAppid                          *uint32            `protobuf:"78,opt"`
		IsConfGroup                             *uint32            `protobuf:"79,opt"`
		IsModifyConfGroupFace                   *uint32            `protobuf:"80,opt"`
		IsModifyConfGroupName                   *uint32            `protobuf:"81,opt"`
		NoFingerOpenFlag                        *uint32            `protobuf:"82,opt"`
		NoCodeFingerOpenFlag                    *uint32            `protobuf:"83,opt"`
		AutoAgreeJoinGroupUserNumForNormalGroup *uint32            `protobuf:"84,opt"`
		AutoAgreeJoinGroupUserNumForConfGroup   *uint32            `protobuf:"85,opt"`
		IsAllowConfGroupMemberNick              *uint32            `protobuf:"86,opt"`
		IsAllowConfGroupMemberAtAll             *uint32            `protobuf:"87,opt"`
		IsAllowConfGroupMemberModifyGroupName   *uint32            `protobuf:"88,opt"`
		LongGroupName                           []byte             `protobuf:"89,opt"`
		CmduinJoinRealMsgSeq                    *uint32            `protobuf:"90,opt"`
		IsGroupFreeze                           *uint32            `protobuf:"91,opt"`
		MsgLimitFrequency                       *uint32            `protobuf:"92,opt"`
		JoinGroupAuth                           []byte             `protobuf:"93,opt"`
		HlGuildAppid                            *uint32            `protobuf:"94,opt"`
		HlGuildSubType                          *uint32            `protobuf:"95,opt"`
		HlGuildOrgid                            *uint32            `protobuf:"96,opt"`
		IsAllowHlGuildBinary                    *uint32            `protobuf:"97,opt"`
		CmduinRingtoneId                        *uint32            `protobuf:"98,opt"`
		GroupFlagext4                           *uint32            `protobuf:"99,opt"`
		GroupFreezeReason                       *uint32            `protobuf:"100,opt"`
		IsAllowRecallMsg                        *uint32            `protobuf:"101,opt"`
		ImportantMsgLatestSeq                   *uint32            `protobuf:"102,opt"`
		GroupSchoolInfo                         []byte             `protobuf:"103,opt"`
		AppealDeadline                          *uint32            `protobuf:"104,opt"`
		StGroupCardPrefix                       *GroupCardPrefix   `protobuf:"105,opt"`
		AllianceId                              *uint64            `protobuf:"106,opt"`
		CmduinFlagEx3Grocery                    *uint32            `protobuf:"107,opt"`
		GroupInfoExtSeq                         *uint32            `protobuf:"108,opt"`
		StGroupInfoExt                          *GroupInfoExt      `protobuf:"109,opt"`
		CmduinGroupRemarkName                   []byte             `protobuf:"110,opt"`
	}

	ReqBody struct {
		Appid           *uint32         `protobuf:"1,opt"`
		Stzreqgroupinfo []*ReqGroupInfo `protobuf:"2"`
		PcClientVersion *uint32         `protobuf:"3,opt"`
	}

	ReqGroupInfo struct {
		GroupCode            *uint64    `protobuf:"1,opt"`
		Stgroupinfo          *GroupInfo `protobuf:"2,opt"`
		LastGetGroupNameTime *uint32    `protobuf:"3,opt"`
	}

	RspBody struct {
		Stzrspgroupinfo []*RspGroupInfo `protobuf:"1"`
		Errorinfo       []byte          `protobuf:"2,opt"`
	}

	RspGroupInfo struct {
		GroupCode   *uint64    `protobuf:"1,opt"`
		Result      *uint32    `protobuf:"2,opt"`
		Stgroupinfo *GroupInfo `protobuf:"3,opt"`
	}

	TagRecord struct {
		FromUin   *uint64 `protobuf:"1,opt"`
		GroupCode *uint64 `protobuf:"2,opt"`
		TagId     []byte  `protobuf:"3,opt"`
		SetTime   *uint64 `protobuf:"4,opt"`
		GoodNum   *uint32 `protobuf:"5,opt"`
		BadNum    *uint32 `protobuf:"6,opt"`
		TagLen    *uint32 `protobuf:"7,opt"`
		TagValue  []byte  `protobuf:"8,opt"`
	}

	GroupInfoExt struct {
		GroupInfoExtSeq     *uint32 `protobuf:"1,opt"`
		LuckyWordId         *uint64 `protobuf:"2,opt"`
		LightCharNum        *uint32 `protobuf:"3,opt"`
		LuckyWord           []byte  `protobuf:"4,opt"`
		StarId              *uint32 `protobuf:"5,opt"`
		EssentialMsgSwitch  *uint32 `protobuf:"6,opt"`
		TodoSeq             *uint32 `protobuf:"7,opt"`
		BlacklistExpireTime *uint32 `protobuf:"8,opt"`
	}
)

func (x *GroupCardPrefix) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *GroupExInfoOnly) GetTribeId() uint32 {
	if x != nil && x.TribeId != nil {
		return *x.TribeId
	}
	return 0
}

func (x *GroupExInfoOnly) GetMoneyForAddGroup() uint32 {
	if x != nil && x.MoneyForAddGroup != nil {
		return *x.MoneyForAddGroup
	}
	return 0
}

func (x *GroupExInfoOnly) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *GroupGeoInfo) GetOwneruin() uint64 {
	if x != nil && x.Owneruin != nil {
		return *x.Owneruin
	}
	return 0
}

func (x *GroupGeoInfo) GetSettime() uint32 {
	if x != nil && x.Settime != nil {
		return *x.Settime
	}
	return 0
}

func (x *GroupGeoInfo) GetCityid() uint32 {
	if x != nil && x.Cityid != nil {
		return *x.Cityid
	}
	return 0
}

func (x *GroupGeoInfo) GetLongitude() int64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *GroupGeoInfo) GetLatitude() int64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GroupGeoInfo) GetPoiId() uint64 {
	if x != nil && x.PoiId != nil {
		return *x.PoiId
	}
	return 0
}

func (x *GroupGeoInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *GroupHeadPortrait) GetPicCnt() uint32 {
	if x != nil && x.PicCnt != nil {
		return *x.PicCnt
	}
	return 0
}

func (x *GroupHeadPortrait) GetDefaultId() uint32 {
	if x != nil && x.DefaultId != nil {
		return *x.DefaultId
	}
	return 0
}

func (x *GroupHeadPortrait) GetVerifyingPicCnt() uint32 {
	if x != nil && x.VerifyingPicCnt != nil {
		return *x.VerifyingPicCnt
	}
	return 0
}

func (x *GroupHeadPortrait) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *GroupHeadPortraitInfo) GetPicId() uint32 {
	if x != nil && x.PicId != nil {
		return *x.PicId
	}
	return 0
}

func (x *GroupHeadPortraitInfo) GetLeftX() uint32 {
	if x != nil && x.LeftX != nil {
		return *x.LeftX
	}
	return 0
}

func (x *GroupHeadPortraitInfo) GetLeftY() uint32 {
	if x != nil && x.LeftY != nil {
		return *x.LeftY
	}
	return 0
}

func (x *GroupHeadPortraitInfo) GetRightX() uint32 {
	if x != nil && x.RightX != nil {
		return *x.RightX
	}
	return 0
}

func (x *GroupHeadPortraitInfo) GetRightY() uint32 {
	if x != nil && x.RightY != nil {
		return *x.RightY
	}
	return 0
}

func (x *GroupHeadPortraitInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *GroupInfo) GetGroupOwner() uint64 {
	if x != nil && x.GroupOwner != nil {
		return *x.GroupOwner
	}
	return 0
}

func (x *GroupInfo) GetGroupCreateTime() uint32 {
	if x != nil && x.GroupCreateTime != nil {
		return *x.GroupCreateTime
	}
	return 0
}

func (x *GroupInfo) GetGroupFlag() uint32 {
	if x != nil && x.GroupFlag != nil {
		return *x.GroupFlag
	}
	return 0
}

func (x *GroupInfo) GetGroupFlagExt() uint32 {
	if x != nil && x.GroupFlagExt != nil {
		return *x.GroupFlagExt
	}
	return 0
}

func (x *GroupInfo) GetGroupMemberMaxNum() uint32 {
	if x != nil && x.GroupMemberMaxNum != nil {
		return *x.GroupMemberMaxNum
	}
	return 0
}

func (x *GroupInfo) GetGroupMemberNum() uint32 {
	if x != nil && x.GroupMemberNum != nil {
		return *x.GroupMemberNum
	}
	return 0
}

func (x *GroupInfo) GetGroupOption() uint32 {
	if x != nil && x.GroupOption != nil {
		return *x.GroupOption
	}
	return 0
}

func (x *GroupInfo) GetGroupClassExt() uint32 {
	if x != nil && x.GroupClassExt != nil {
		return *x.GroupClassExt
	}
	return 0
}

func (x *GroupInfo) GetGroupSpecialClass() uint32 {
	if x != nil && x.GroupSpecialClass != nil {
		return *x.GroupSpecialClass
	}
	return 0
}

func (x *GroupInfo) GetGroupLevel() uint32 {
	if x != nil && x.GroupLevel != nil {
		return *x.GroupLevel
	}
	return 0
}

func (x *GroupInfo) GetGroupFace() uint32 {
	if x != nil && x.GroupFace != nil {
		return *x.GroupFace
	}
	return 0
}

func (x *GroupInfo) GetGroupDefaultPage() uint32 {
	if x != nil && x.GroupDefaultPage != nil {
		return *x.GroupDefaultPage
	}
	return 0
}

func (x *GroupInfo) GetGroupInfoSeq() uint32 {
	if x != nil && x.GroupInfoSeq != nil {
		return *x.GroupInfoSeq
	}
	return 0
}

func (x *GroupInfo) GetGroupRoamingTime() uint32 {
	if x != nil && x.GroupRoamingTime != nil {
		return *x.GroupRoamingTime
	}
	return 0
}

func (x *GroupInfo) GetGroupExtraAdmNum() uint32 {
	if x != nil && x.GroupExtraAdmNum != nil {
		return *x.GroupExtraAdmNum
	}
	return 0
}

func (x *GroupInfo) GetGroupUin() uint64 {
	if x != nil && x.GroupUin != nil {
		return *x.GroupUin
	}
	return 0
}

func (x *GroupInfo) GetGroupCurMsgSeq() uint32 {
	if x != nil && x.GroupCurMsgSeq != nil {
		return *x.GroupCurMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetGroupLastMsgTime() uint32 {
	if x != nil && x.GroupLastMsgTime != nil {
		return *x.GroupLastMsgTime
	}
	return 0
}

func (x *GroupInfo) GetGroupVisitorMaxNum() uint32 {
	if x != nil && x.GroupVisitorMaxNum != nil {
		return *x.GroupVisitorMaxNum
	}
	return 0
}

func (x *GroupInfo) GetGroupVisitorCurNum() uint32 {
	if x != nil && x.GroupVisitorCurNum != nil {
		return *x.GroupVisitorCurNum
	}
	return 0
}

func (x *GroupInfo) GetLevelNameSeq() uint32 {
	if x != nil && x.LevelNameSeq != nil {
		return *x.LevelNameSeq
	}
	return 0
}

func (x *GroupInfo) GetGroupAdminMaxNum() uint32 {
	if x != nil && x.GroupAdminMaxNum != nil {
		return *x.GroupAdminMaxNum
	}
	return 0
}

func (x *GroupInfo) GetGroupAioSkinTimestamp() uint32 {
	if x != nil && x.GroupAioSkinTimestamp != nil {
		return *x.GroupAioSkinTimestamp
	}
	return 0
}

func (x *GroupInfo) GetGroupBoardSkinTimestamp() uint32 {
	if x != nil && x.GroupBoardSkinTimestamp != nil {
		return *x.GroupBoardSkinTimestamp
	}
	return 0
}

func (x *GroupInfo) GetGroupCoverSkinTimestamp() uint32 {
	if x != nil && x.GroupCoverSkinTimestamp != nil {
		return *x.GroupCoverSkinTimestamp
	}
	return 0
}

func (x *GroupInfo) GetGroupGrade() uint32 {
	if x != nil && x.GroupGrade != nil {
		return *x.GroupGrade
	}
	return 0
}

func (x *GroupInfo) GetActiveMemberNum() uint32 {
	if x != nil && x.ActiveMemberNum != nil {
		return *x.ActiveMemberNum
	}
	return 0
}

func (x *GroupInfo) GetCertificationType() uint32 {
	if x != nil && x.CertificationType != nil {
		return *x.CertificationType
	}
	return 0
}

func (x *GroupInfo) GetHeadPortraitSeq() uint32 {
	if x != nil && x.HeadPortraitSeq != nil {
		return *x.HeadPortraitSeq
	}
	return 0
}

func (x *GroupInfo) GetShutupTimestamp() uint32 {
	if x != nil && x.ShutupTimestamp != nil {
		return *x.ShutupTimestamp
	}
	return 0
}

func (x *GroupInfo) GetShutupTimestampMe() uint32 {
	if x != nil && x.ShutupTimestampMe != nil {
		return *x.ShutupTimestampMe
	}
	return 0
}

func (x *GroupInfo) GetCreateSourceFlag() uint32 {
	if x != nil && x.CreateSourceFlag != nil {
		return *x.CreateSourceFlag
	}
	return 0
}

func (x *GroupInfo) GetCmduinMsgSeq() uint32 {
	if x != nil && x.CmduinMsgSeq != nil {
		return *x.CmduinMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetCmduinJoinTime() uint32 {
	if x != nil && x.CmduinJoinTime != nil {
		return *x.CmduinJoinTime
	}
	return 0
}

func (x *GroupInfo) GetCmduinUinFlag() uint32 {
	if x != nil && x.CmduinUinFlag != nil {
		return *x.CmduinUinFlag
	}
	return 0
}

func (x *GroupInfo) GetCmduinFlagEx() uint32 {
	if x != nil && x.CmduinFlagEx != nil {
		return *x.CmduinFlagEx
	}
	return 0
}

func (x *GroupInfo) GetCmduinNewMobileFlag() uint32 {
	if x != nil && x.CmduinNewMobileFlag != nil {
		return *x.CmduinNewMobileFlag
	}
	return 0
}

func (x *GroupInfo) GetCmduinReadMsgSeq() uint32 {
	if x != nil && x.CmduinReadMsgSeq != nil {
		return *x.CmduinReadMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetCmduinLastMsgTime() uint32 {
	if x != nil && x.CmduinLastMsgTime != nil {
		return *x.CmduinLastMsgTime
	}
	return 0
}

func (x *GroupInfo) GetGroupTypeFlag() uint32 {
	if x != nil && x.GroupTypeFlag != nil {
		return *x.GroupTypeFlag
	}
	return 0
}

func (x *GroupInfo) GetAppPrivilegeFlag() uint32 {
	if x != nil && x.AppPrivilegeFlag != nil {
		return *x.AppPrivilegeFlag
	}
	return 0
}

func (x *GroupInfo) GetGroupSecLevel() uint32 {
	if x != nil && x.GroupSecLevel != nil {
		return *x.GroupSecLevel
	}
	return 0
}

func (x *GroupInfo) GetGroupSecLevelInfo() uint32 {
	if x != nil && x.GroupSecLevelInfo != nil {
		return *x.GroupSecLevelInfo
	}
	return 0
}

func (x *GroupInfo) GetCmduinPrivilege() uint32 {
	if x != nil && x.CmduinPrivilege != nil {
		return *x.CmduinPrivilege
	}
	return 0
}

func (x *GroupInfo) GetCmduinFlagEx2() uint32 {
	if x != nil && x.CmduinFlagEx2 != nil {
		return *x.CmduinFlagEx2
	}
	return 0
}

func (x *GroupInfo) GetConfUin() uint64 {
	if x != nil && x.ConfUin != nil {
		return *x.ConfUin
	}
	return 0
}

func (x *GroupInfo) GetConfMaxMsgSeq() uint32 {
	if x != nil && x.ConfMaxMsgSeq != nil {
		return *x.ConfMaxMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetConfToGroupTime() uint32 {
	if x != nil && x.ConfToGroupTime != nil {
		return *x.ConfToGroupTime
	}
	return 0
}

func (x *GroupInfo) GetPasswordRedbagTime() uint32 {
	if x != nil && x.PasswordRedbagTime != nil {
		return *x.PasswordRedbagTime
	}
	return 0
}

func (x *GroupInfo) GetSubscriptionUin() uint64 {
	if x != nil && x.SubscriptionUin != nil {
		return *x.SubscriptionUin
	}
	return 0
}

func (x *GroupInfo) GetMemberListChangeSeq() uint32 {
	if x != nil && x.MemberListChangeSeq != nil {
		return *x.MemberListChangeSeq
	}
	return 0
}

func (x *GroupInfo) GetMembercardSeq() uint32 {
	if x != nil && x.MembercardSeq != nil {
		return *x.MembercardSeq
	}
	return 0
}

func (x *GroupInfo) GetRootId() uint64 {
	if x != nil && x.RootId != nil {
		return *x.RootId
	}
	return 0
}

func (x *GroupInfo) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *GroupInfo) GetTeamSeq() uint32 {
	if x != nil && x.TeamSeq != nil {
		return *x.TeamSeq
	}
	return 0
}

func (x *GroupInfo) GetHistoryMsgBeginTime() uint64 {
	if x != nil && x.HistoryMsgBeginTime != nil {
		return *x.HistoryMsgBeginTime
	}
	return 0
}

func (x *GroupInfo) GetInviteNoAuthNumLimit() uint64 {
	if x != nil && x.InviteNoAuthNumLimit != nil {
		return *x.InviteNoAuthNumLimit
	}
	return 0
}

func (x *GroupInfo) GetCmduinHistoryMsgSeq() uint32 {
	if x != nil && x.CmduinHistoryMsgSeq != nil {
		return *x.CmduinHistoryMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetCmduinJoinMsgSeq() uint32 {
	if x != nil && x.CmduinJoinMsgSeq != nil {
		return *x.CmduinJoinMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetGroupFlagext3() uint32 {
	if x != nil && x.GroupFlagext3 != nil {
		return *x.GroupFlagext3
	}
	return 0
}

func (x *GroupInfo) GetGroupOpenAppid() uint32 {
	if x != nil && x.GroupOpenAppid != nil {
		return *x.GroupOpenAppid
	}
	return 0
}

func (x *GroupInfo) GetIsConfGroup() uint32 {
	if x != nil && x.IsConfGroup != nil {
		return *x.IsConfGroup
	}
	return 0
}

func (x *GroupInfo) GetIsModifyConfGroupFace() uint32 {
	if x != nil && x.IsModifyConfGroupFace != nil {
		return *x.IsModifyConfGroupFace
	}
	return 0
}

func (x *GroupInfo) GetIsModifyConfGroupName() uint32 {
	if x != nil && x.IsModifyConfGroupName != nil {
		return *x.IsModifyConfGroupName
	}
	return 0
}

func (x *GroupInfo) GetNoFingerOpenFlag() uint32 {
	if x != nil && x.NoFingerOpenFlag != nil {
		return *x.NoFingerOpenFlag
	}
	return 0
}

func (x *GroupInfo) GetNoCodeFingerOpenFlag() uint32 {
	if x != nil && x.NoCodeFingerOpenFlag != nil {
		return *x.NoCodeFingerOpenFlag
	}
	return 0
}

func (x *GroupInfo) GetAutoAgreeJoinGroupUserNumForNormalGroup() uint32 {
	if x != nil && x.AutoAgreeJoinGroupUserNumForNormalGroup != nil {
		return *x.AutoAgreeJoinGroupUserNumForNormalGroup
	}
	return 0
}

func (x *GroupInfo) GetAutoAgreeJoinGroupUserNumForConfGroup() uint32 {
	if x != nil && x.AutoAgreeJoinGroupUserNumForConfGroup != nil {
		return *x.AutoAgreeJoinGroupUserNumForConfGroup
	}
	return 0
}

func (x *GroupInfo) GetIsAllowConfGroupMemberNick() uint32 {
	if x != nil && x.IsAllowConfGroupMemberNick != nil {
		return *x.IsAllowConfGroupMemberNick
	}
	return 0
}

func (x *GroupInfo) GetIsAllowConfGroupMemberAtAll() uint32 {
	if x != nil && x.IsAllowConfGroupMemberAtAll != nil {
		return *x.IsAllowConfGroupMemberAtAll
	}
	return 0
}

func (x *GroupInfo) GetIsAllowConfGroupMemberModifyGroupName() uint32 {
	if x != nil && x.IsAllowConfGroupMemberModifyGroupName != nil {
		return *x.IsAllowConfGroupMemberModifyGroupName
	}
	return 0
}

func (x *GroupInfo) GetCmduinJoinRealMsgSeq() uint32 {
	if x != nil && x.CmduinJoinRealMsgSeq != nil {
		return *x.CmduinJoinRealMsgSeq
	}
	return 0
}

func (x *GroupInfo) GetIsGroupFreeze() uint32 {
	if x != nil && x.IsGroupFreeze != nil {
		return *x.IsGroupFreeze
	}
	return 0
}

func (x *GroupInfo) GetMsgLimitFrequency() uint32 {
	if x != nil && x.MsgLimitFrequency != nil {
		return *x.MsgLimitFrequency
	}
	return 0
}

func (x *GroupInfo) GetHlGuildAppid() uint32 {
	if x != nil && x.HlGuildAppid != nil {
		return *x.HlGuildAppid
	}
	return 0
}

func (x *GroupInfo) GetHlGuildSubType() uint32 {
	if x != nil && x.HlGuildSubType != nil {
		return *x.HlGuildSubType
	}
	return 0
}

func (x *GroupInfo) GetHlGuildOrgid() uint32 {
	if x != nil && x.HlGuildOrgid != nil {
		return *x.HlGuildOrgid
	}
	return 0
}

func (x *GroupInfo) GetIsAllowHlGuildBinary() uint32 {
	if x != nil && x.IsAllowHlGuildBinary != nil {
		return *x.IsAllowHlGuildBinary
	}
	return 0
}

func (x *GroupInfo) GetCmduinRingtoneId() uint32 {
	if x != nil && x.CmduinRingtoneId != nil {
		return *x.CmduinRingtoneId
	}
	return 0
}

func (x *GroupInfo) GetGroupFlagext4() uint32 {
	if x != nil && x.GroupFlagext4 != nil {
		return *x.GroupFlagext4
	}
	return 0
}

func (x *GroupInfo) GetGroupFreezeReason() uint32 {
	if x != nil && x.GroupFreezeReason != nil {
		return *x.GroupFreezeReason
	}
	return 0
}

func (x *GroupInfo) GetIsAllowRecallMsg() uint32 {
	if x != nil && x.IsAllowRecallMsg != nil {
		return *x.IsAllowRecallMsg
	}
	return 0
}

func (x *GroupInfo) GetImportantMsgLatestSeq() uint32 {
	if x != nil && x.ImportantMsgLatestSeq != nil {
		return *x.ImportantMsgLatestSeq
	}
	return 0
}

func (x *GroupInfo) GetAppealDeadline() uint32 {
	if x != nil && x.AppealDeadline != nil {
		return *x.AppealDeadline
	}
	return 0
}

func (x *GroupInfo) GetAllianceId() uint64 {
	if x != nil && x.AllianceId != nil {
		return *x.AllianceId
	}
	return 0
}

func (x *GroupInfo) GetCmduinFlagEx3Grocery() uint32 {
	if x != nil && x.CmduinFlagEx3Grocery != nil {
		return *x.CmduinFlagEx3Grocery
	}
	return 0
}

func (x *GroupInfo) GetGroupInfoExtSeq() uint32 {
	if x != nil && x.GroupInfoExtSeq != nil {
		return *x.GroupInfoExtSeq
	}
	return 0
}

func (x *GroupInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *ReqBody) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *ReqBody) GetPcClientVersion() uint32 {
	if x != nil && x.PcClientVersion != nil {
		return *x.PcClientVersion
	}
	return 0
}

func (x *ReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *ReqGroupInfo) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *ReqGroupInfo) GetLastGetGroupNameTime() uint32 {
	if x != nil && x.LastGetGroupNameTime != nil {
		return *x.LastGetGroupNameTime
	}
	return 0
}

func (x *ReqGroupInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *RspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *RspGroupInfo) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *RspGroupInfo) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *RspGroupInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *TagRecord) GetFromUin() uint64 {
	if x != nil && x.FromUin != nil {
		return *x.FromUin
	}
	return 0
}

func (x *TagRecord) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *TagRecord) GetSetTime() uint64 {
	if x != nil && x.SetTime != nil {
		return *x.SetTime
	}
	return 0
}

func (x *TagRecord) GetGoodNum() uint32 {
	if x != nil && x.GoodNum != nil {
		return *x.GoodNum
	}
	return 0
}

func (x *TagRecord) GetBadNum() uint32 {
	if x != nil && x.BadNum != nil {
		return *x.BadNum
	}
	return 0
}

func (x *TagRecord) GetTagLen() uint32 {
	if x != nil && x.TagLen != nil {
		return *x.TagLen
	}
	return 0
}

func (x *TagRecord) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *GroupInfoExt) GetGroupInfoExtSeq() uint32 {
	if x != nil && x.GroupInfoExtSeq != nil {
		return *x.GroupInfoExtSeq
	}
	return 0
}

func (x *GroupInfoExt) GetLuckyWordId() uint64 {
	if x != nil && x.LuckyWordId != nil {
		return *x.LuckyWordId
	}
	return 0
}

func (x *GroupInfoExt) GetLightCharNum() uint32 {
	if x != nil && x.LightCharNum != nil {
		return *x.LightCharNum
	}
	return 0
}

func (x *GroupInfoExt) GetStarId() uint32 {
	if x != nil && x.StarId != nil {
		return *x.StarId
	}
	return 0
}

func (x *GroupInfoExt) GetEssentialMsgSwitch() uint32 {
	if x != nil && x.EssentialMsgSwitch != nil {
		return *x.EssentialMsgSwitch
	}
	return 0
}

func (x *GroupInfoExt) GetTodoSeq() uint32 {
	if x != nil && x.TodoSeq != nil {
		return *x.TodoSeq
	}
	return 0
}

func (x *GroupInfoExt) GetBlacklistExpireTime() uint32 {
	if x != nil && x.BlacklistExpireTime != nil {
		return *x.BlacklistExpireTime
	}
	return 0
}

func (x *GroupInfoExt) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}
