// Code generated by yaprotoc. DO NOT EDIT.
// source: channel/unknown.proto

package channel

import (
	"github.com/pkg/errors"
	"github.com/segmentio/encoding/proto"
)

type ChannelListRsp struct {
	GuildId  *uint64             `protobuf:"varint,1,opt"`
	Channels []*GuildChannelInfo `protobuf:"bytes,2,rep"`
}

func (x *ChannelListRsp) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *ChannelListRsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ChannelOidb0Xf55Rsp struct {
	Info *GuildChannelInfo `protobuf:"bytes,1,opt"`
}

func (x *ChannelOidb0Xf55Rsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ChannelOidb0Xf57Rsp struct {
	Rsp *GuildMetaRsp `protobuf:"bytes,1,opt"`
}

func (x *ChannelOidb0Xf57Rsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ChannelOidb0Xf5BRsp struct {
	GuildId   *uint64            `protobuf:"varint,1,opt"`
	Bots      []*GuildMemberInfo `protobuf:"bytes,4,rep"`
	Members   []*GuildMemberInfo `protobuf:"bytes,5,rep"`
	AdminInfo *GuildAdminInfo    `protobuf:"bytes,25,opt"`
}

func (x *ChannelOidb0Xf5BRsp) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *ChannelOidb0Xf5BRsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ChannelOidb0Xf5DRsp struct {
	Rsp *ChannelListRsp `protobuf:"bytes,1,opt"`
}

func (x *ChannelOidb0Xf5DRsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ChannelOidb0Xf88Rsp struct {
	Profile *GuildUserProfile `protobuf:"bytes,1,opt"`
}

func (x *ChannelOidb0Xf88Rsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ChannelOidb0Xfc9Rsp struct {
	Profile *GuildUserProfile `protobuf:"bytes,1,opt"`
}

func (x *ChannelOidb0Xfc9Rsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildAdminInfo struct {
	Admins []*GuildMemberInfo `protobuf:"bytes,2,rep"`
}

func (x *GuildAdminInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildChannelInfo struct {
	ChannelId          *uint64                     `protobuf:"varint,1,opt"`
	ChannelName        *string                     `protobuf:"bytes,2,opt"`
	CreatorUin         *int64                      `protobuf:"varint,3,opt"`
	CreateTime         *int64                      `protobuf:"varint,4,opt"`
	GuildId            *uint64                     `protobuf:"varint,5,opt"`
	FinalNotifyType    *int32                      `protobuf:"varint,6,opt"`
	ChannelType        *int32                      `protobuf:"varint,7,opt"`
	TalkPermission     *int32                      `protobuf:"varint,8,opt"`
	CreatorTinyId      *uint64                     `protobuf:"varint,15,opt"`
	VisibleType        *int32                      `protobuf:"varint,22,opt"`
	TopMsg             *GuildChannelTopMsgInfo     `protobuf:"bytes,28,opt"`
	CurrentSlowModeKey *int32                      `protobuf:"varint,31,opt"`
	SlowModeInfos      []*GuildChannelSlowModeInfo `protobuf:"bytes,32,rep"`
}

func (x *GuildChannelInfo) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *GuildChannelInfo) GetChannelName() string {
	if x != nil && x.ChannelName != nil {
		return *x.ChannelName
	}
	return ""
}

func (x *GuildChannelInfo) GetCreatorUin() int64 {
	if x != nil && x.CreatorUin != nil {
		return *x.CreatorUin
	}
	return 0
}

func (x *GuildChannelInfo) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *GuildChannelInfo) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildChannelInfo) GetFinalNotifyType() int32 {
	if x != nil && x.FinalNotifyType != nil {
		return *x.FinalNotifyType
	}
	return 0
}

func (x *GuildChannelInfo) GetChannelType() int32 {
	if x != nil && x.ChannelType != nil {
		return *x.ChannelType
	}
	return 0
}

func (x *GuildChannelInfo) GetTalkPermission() int32 {
	if x != nil && x.TalkPermission != nil {
		return *x.TalkPermission
	}
	return 0
}

func (x *GuildChannelInfo) GetCreatorTinyId() uint64 {
	if x != nil && x.CreatorTinyId != nil {
		return *x.CreatorTinyId
	}
	return 0
}

func (x *GuildChannelInfo) GetVisibleType() int32 {
	if x != nil && x.VisibleType != nil {
		return *x.VisibleType
	}
	return 0
}

func (x *GuildChannelInfo) GetCurrentSlowModeKey() int32 {
	if x != nil && x.CurrentSlowModeKey != nil {
		return *x.CurrentSlowModeKey
	}
	return 0
}

func (x *GuildChannelInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildChannelSlowModeInfo struct {
	SlowModeKey    *int32  `protobuf:"varint,1,opt"`
	SpeakFrequency *int32  `protobuf:"varint,2,opt"`
	SlowModeCircle *int32  `protobuf:"varint,3,opt"`
	SlowModeText   *string `protobuf:"bytes,4,opt"`
}

func (x *GuildChannelSlowModeInfo) GetSlowModeKey() int32 {
	if x != nil && x.SlowModeKey != nil {
		return *x.SlowModeKey
	}
	return 0
}

func (x *GuildChannelSlowModeInfo) GetSpeakFrequency() int32 {
	if x != nil && x.SpeakFrequency != nil {
		return *x.SpeakFrequency
	}
	return 0
}

func (x *GuildChannelSlowModeInfo) GetSlowModeCircle() int32 {
	if x != nil && x.SlowModeCircle != nil {
		return *x.SlowModeCircle
	}
	return 0
}

func (x *GuildChannelSlowModeInfo) GetSlowModeText() string {
	if x != nil && x.SlowModeText != nil {
		return *x.SlowModeText
	}
	return ""
}

func (x *GuildChannelSlowModeInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildChannelTopMsgInfo struct {
	TopMsgSeq            *uint64 `protobuf:"varint,1,opt"`
	TopMsgTime           *int64  `protobuf:"varint,2,opt"`
	TopMsgOperatorTinyId *uint64 `protobuf:"varint,3,opt"`
}

func (x *GuildChannelTopMsgInfo) GetTopMsgSeq() uint64 {
	if x != nil && x.TopMsgSeq != nil {
		return *x.TopMsgSeq
	}
	return 0
}

func (x *GuildChannelTopMsgInfo) GetTopMsgTime() int64 {
	if x != nil && x.TopMsgTime != nil {
		return *x.TopMsgTime
	}
	return 0
}

func (x *GuildChannelTopMsgInfo) GetTopMsgOperatorTinyId() uint64 {
	if x != nil && x.TopMsgOperatorTinyId != nil {
		return *x.TopMsgOperatorTinyId
	}
	return 0
}

func (x *GuildChannelTopMsgInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildMemberInfo struct {
	Title         *string `protobuf:"bytes,2,opt"`
	Nickname      *string `protobuf:"bytes,3,opt"`
	LastSpeakTime *int64  `protobuf:"varint,4,opt"`
	Role          *int32  `protobuf:"varint,5,opt"`
	TinyId        *uint64 `protobuf:"varint,8,opt"`
}

func (x *GuildMemberInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *GuildMemberInfo) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *GuildMemberInfo) GetLastSpeakTime() int64 {
	if x != nil && x.LastSpeakTime != nil {
		return *x.LastSpeakTime
	}
	return 0
}

func (x *GuildMemberInfo) GetRole() int32 {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return 0
}

func (x *GuildMemberInfo) GetTinyId() uint64 {
	if x != nil && x.TinyId != nil {
		return *x.TinyId
	}
	return 0
}

func (x *GuildMemberInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildMeta struct {
	GuildCode      *uint64 `protobuf:"varint,2,opt"`
	CreateTime     *int64  `protobuf:"varint,4,opt"`
	MaxMemberCount *int64  `protobuf:"varint,5,opt"`
	MemberCount    *int64  `protobuf:"varint,6,opt"`
	Name           *string `protobuf:"bytes,8,opt"`
	RobotMaxNum    *int32  `protobuf:"varint,11,opt"`
	AdminMaxNum    *int32  `protobuf:"varint,12,opt"`
	Profile        *string `protobuf:"bytes,13,opt"`
	AvatarSeq      *int64  `protobuf:"varint,14,opt"`
	OwnerId        *uint64 `protobuf:"varint,18,opt"`
	CoverSeq       *int64  `protobuf:"varint,19,opt"`
	ClientId       *int32  `protobuf:"varint,20,opt"`
}

func (x *GuildMeta) GetGuildCode() uint64 {
	if x != nil && x.GuildCode != nil {
		return *x.GuildCode
	}
	return 0
}

func (x *GuildMeta) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *GuildMeta) GetMaxMemberCount() int64 {
	if x != nil && x.MaxMemberCount != nil {
		return *x.MaxMemberCount
	}
	return 0
}

func (x *GuildMeta) GetMemberCount() int64 {
	if x != nil && x.MemberCount != nil {
		return *x.MemberCount
	}
	return 0
}

func (x *GuildMeta) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GuildMeta) GetRobotMaxNum() int32 {
	if x != nil && x.RobotMaxNum != nil {
		return *x.RobotMaxNum
	}
	return 0
}

func (x *GuildMeta) GetAdminMaxNum() int32 {
	if x != nil && x.AdminMaxNum != nil {
		return *x.AdminMaxNum
	}
	return 0
}

func (x *GuildMeta) GetProfile() string {
	if x != nil && x.Profile != nil {
		return *x.Profile
	}
	return ""
}

func (x *GuildMeta) GetAvatarSeq() int64 {
	if x != nil && x.AvatarSeq != nil {
		return *x.AvatarSeq
	}
	return 0
}

func (x *GuildMeta) GetOwnerId() uint64 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

func (x *GuildMeta) GetCoverSeq() int64 {
	if x != nil && x.CoverSeq != nil {
		return *x.CoverSeq
	}
	return 0
}

func (x *GuildMeta) GetClientId() int32 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *GuildMeta) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildMetaRsp struct {
	GuildId *uint64    `protobuf:"varint,3,opt"`
	Meta    *GuildMeta `protobuf:"bytes,4,opt"`
}

func (x *GuildMetaRsp) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildMetaRsp) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GuildUserProfile struct {
	TinyId    *uint64 `protobuf:"varint,2,opt"`
	Nickname  *string `protobuf:"bytes,3,opt"`
	AvatarUrl *string `protobuf:"bytes,6,opt"`
	JoinTime  *int64  `protobuf:"varint,16,opt"`
}

func (x *GuildUserProfile) GetTinyId() uint64 {
	if x != nil && x.TinyId != nil {
		return *x.TinyId
	}
	return 0
}

func (x *GuildUserProfile) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *GuildUserProfile) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *GuildUserProfile) GetJoinTime() int64 {
	if x != nil && x.JoinTime != nil {
		return *x.JoinTime
	}
	return 0
}

func (x *GuildUserProfile) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}
