// Code generated by Proto2Go.Net. Only used for MiraiGo. DO NOT EDIT.
// Source: oidb0x6d6.proto

package oidb0x6d6

import (
	"github.com/pkg/errors"
	"go.dedis.ch/protobuf"
)

type (
	DeleteFileReqBody struct {
		GroupCode      *uint64 `protobuf:"1,opt"`
		AppId          *uint32 `protobuf:"2,opt"`
		BusId          *uint32 `protobuf:"3,opt"`
		ParentFolderId *string `protobuf:"4,opt"`
		FileId         *string `protobuf:"5,opt"`
		MsgdbSeq       *uint32 `protobuf:"6,opt"`
		MsgRand        *uint32 `protobuf:"7,opt"`
	}

	DeleteFileRspBody struct {
		RetCode       *int32  `protobuf:"1,opt"`
		RetMsg        *string `protobuf:"2,opt"`
		ClientWording *string `protobuf:"3,opt"`
	}

	DownloadFileReqBody struct {
		GroupCode    *uint64 `protobuf:"1,opt"`
		AppId        *uint32 `protobuf:"2,opt"`
		BusId        *uint32 `protobuf:"3,opt"`
		FileId       *string `protobuf:"4,opt"`
		ThumbnailReq *bool   `protobuf:"5,opt"`
		UrlType      *uint32 `protobuf:"6,opt"`
		PreviewReq   *bool   `protobuf:"7,opt"`
		Src          *uint32 `protobuf:"8,opt"`
	}

	DownloadFileRspBody struct {
		RetCode          *int32  `protobuf:"1,opt"`
		RetMsg           *string `protobuf:"2,opt"`
		ClientWording    *string `protobuf:"3,opt"`
		DownloadIp       *string `protobuf:"4,opt"`
		DownloadDns      []byte  `protobuf:"5,opt"`
		DownloadUrl      []byte  `protobuf:"6,opt"`
		Sha              []byte  `protobuf:"7,opt"`
		Sha3             []byte  `protobuf:"8,opt"`
		Md5              []byte  `protobuf:"9,opt"`
		CookieVal        []byte  `protobuf:"10,opt"`
		SaveFileName     *string `protobuf:"11,opt"`
		PreviewPort      *uint32 `protobuf:"12,opt"`
		DownloadDnsHttps *string `protobuf:"13,opt"`
		PreviewPortHttps *uint32 `protobuf:"14,opt"`
	}

	MoveFileReqBody struct {
		GroupCode      *uint64 `protobuf:"1,opt"`
		AppId          *uint32 `protobuf:"2,opt"`
		BusId          *uint32 `protobuf:"3,opt"`
		FileId         *string `protobuf:"4,opt"`
		ParentFolderId *string `protobuf:"5,opt"`
		DestFolderId   *string `protobuf:"6,opt"`
	}

	MoveFileRspBody struct {
		RetCode        *int32  `protobuf:"1,opt"`
		RetMsg         *string `protobuf:"2,opt"`
		ClientWording  *string `protobuf:"3,opt"`
		ParentFolderId *string `protobuf:"4,opt"`
	}

	RenameFileReqBody struct {
		GroupCode      *uint64 `protobuf:"1,opt"`
		AppId          *uint32 `protobuf:"2,opt"`
		BusId          *uint32 `protobuf:"3,opt"`
		FileId         *string `protobuf:"4,opt"`
		ParentFolderId *string `protobuf:"5,opt"`
		NewFileName    *string `protobuf:"6,opt"`
	}

	RenameFileRspBody struct {
		RetCode       *int32  `protobuf:"1,opt"`
		RetMsg        *string `protobuf:"2,opt"`
		ClientWording *string `protobuf:"3,opt"`
	}

	ReqBody struct {
		UploadFileReq   *UploadFileReqBody   `protobuf:"1,opt"`
		ResendFileReq   *ResendReqBody       `protobuf:"2,opt"`
		DownloadFileReq *DownloadFileReqBody `protobuf:"3,opt"`
		DeleteFileReq   *DeleteFileReqBody   `protobuf:"4,opt"`
		RenameFileReq   *RenameFileReqBody   `protobuf:"5,opt"`
		MoveFileReq     *MoveFileReqBody     `protobuf:"6,opt"`
	}

	ResendReqBody struct {
		GroupCode *uint64 `protobuf:"1,opt"`
		AppId     *uint32 `protobuf:"2,opt"`
		BusId     *uint32 `protobuf:"3,opt"`
		FileId    *string `protobuf:"4,opt"`
		Sha       []byte  `protobuf:"5,opt"`
	}

	ResendRspBody struct {
		RetCode       *int32  `protobuf:"1,opt"`
		RetMsg        *string `protobuf:"2,opt"`
		ClientWording *string `protobuf:"3,opt"`
		UploadIp      *string `protobuf:"4,opt"`
		FileKey       []byte  `protobuf:"5,opt"`
		CheckKey      []byte  `protobuf:"6,opt"`
	}

	RspBody struct {
		UploadFileRsp   *UploadFileRspBody   `protobuf:"1,opt"`
		ResendFileRsp   *ResendRspBody       `protobuf:"2,opt"`
		DownloadFileRsp *DownloadFileRspBody `protobuf:"3,opt"`
		DeleteFileRsp   *DeleteFileRspBody   `protobuf:"4,opt"`
		RenameFileRsp   *RenameFileRspBody   `protobuf:"5,opt"`
		MoveFileRsp     *MoveFileRspBody     `protobuf:"6,opt"`
	}

	UploadFileReqBody struct {
		GroupCode          *uint64 `protobuf:"1,opt"`
		AppId              *uint32 `protobuf:"2,opt"`
		BusId              *uint32 `protobuf:"3,opt"`
		Entrance           *uint32 `protobuf:"4,opt"`
		ParentFolderId     *string `protobuf:"5,opt"`
		FileName           *string `protobuf:"6,opt"`
		LocalPath          *string `protobuf:"7,opt"`
		FileSize           *uint64 `protobuf:"8,opt"`
		Sha                []byte  `protobuf:"9,opt"`
		Sha3               []byte  `protobuf:"10,opt"`
		Md5                []byte  `protobuf:"11,opt"`
		SupportMultiUpload *bool   `protobuf:"15,opt"`
	}

	UploadFileRspBody struct {
		RetCode       *int32   `protobuf:"1,opt"`
		RetMsg        *string  `protobuf:"2,opt"`
		ClientWording *string  `protobuf:"3,opt"`
		UploadIp      *string  `protobuf:"4,opt"`
		ServerDns     *string  `protobuf:"5,opt"`
		BusId         *uint32  `protobuf:"6,opt"`
		FileId        *string  `protobuf:"7,opt"`
		FileKey       []byte   `protobuf:"8,opt"`
		CheckKey      []byte   `protobuf:"9,opt"`
		FileExist     *bool    `protobuf:"10,opt"`
		UploadIpLanV4 []string `protobuf:"12"`
		UploadIpLanV6 []string `protobuf:"13"`
		UploadPort    *uint32  `protobuf:"14,opt"`
	}
)

func (x *DeleteFileReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *DeleteFileReqBody) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *DeleteFileReqBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *DeleteFileReqBody) GetParentFolderId() string {
	if x != nil && x.ParentFolderId != nil {
		return *x.ParentFolderId
	}
	return ""
}

func (x *DeleteFileReqBody) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *DeleteFileReqBody) GetMsgdbSeq() uint32 {
	if x != nil && x.MsgdbSeq != nil {
		return *x.MsgdbSeq
	}
	return 0
}

func (x *DeleteFileReqBody) GetMsgRand() uint32 {
	if x != nil && x.MsgRand != nil {
		return *x.MsgRand
	}
	return 0
}

func (x *DeleteFileReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *DeleteFileRspBody) GetRetCode() int32 {
	if x != nil && x.RetCode != nil {
		return *x.RetCode
	}
	return 0
}

func (x *DeleteFileRspBody) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *DeleteFileRspBody) GetClientWording() string {
	if x != nil && x.ClientWording != nil {
		return *x.ClientWording
	}
	return ""
}

func (x *DeleteFileRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *DownloadFileReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *DownloadFileReqBody) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *DownloadFileReqBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *DownloadFileReqBody) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *DownloadFileReqBody) GetThumbnailReq() bool {
	if x != nil && x.ThumbnailReq != nil {
		return *x.ThumbnailReq
	}
	return false
}

func (x *DownloadFileReqBody) GetUrlType() uint32 {
	if x != nil && x.UrlType != nil {
		return *x.UrlType
	}
	return 0
}

func (x *DownloadFileReqBody) GetPreviewReq() bool {
	if x != nil && x.PreviewReq != nil {
		return *x.PreviewReq
	}
	return false
}

func (x *DownloadFileReqBody) GetSrc() uint32 {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return 0
}

func (x *DownloadFileReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *DownloadFileRspBody) GetRetCode() int32 {
	if x != nil && x.RetCode != nil {
		return *x.RetCode
	}
	return 0
}

func (x *DownloadFileRspBody) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *DownloadFileRspBody) GetClientWording() string {
	if x != nil && x.ClientWording != nil {
		return *x.ClientWording
	}
	return ""
}

func (x *DownloadFileRspBody) GetDownloadIp() string {
	if x != nil && x.DownloadIp != nil {
		return *x.DownloadIp
	}
	return ""
}

func (x *DownloadFileRspBody) GetSaveFileName() string {
	if x != nil && x.SaveFileName != nil {
		return *x.SaveFileName
	}
	return ""
}

func (x *DownloadFileRspBody) GetPreviewPort() uint32 {
	if x != nil && x.PreviewPort != nil {
		return *x.PreviewPort
	}
	return 0
}

func (x *DownloadFileRspBody) GetDownloadDnsHttps() string {
	if x != nil && x.DownloadDnsHttps != nil {
		return *x.DownloadDnsHttps
	}
	return ""
}

func (x *DownloadFileRspBody) GetPreviewPortHttps() uint32 {
	if x != nil && x.PreviewPortHttps != nil {
		return *x.PreviewPortHttps
	}
	return 0
}

func (x *DownloadFileRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *MoveFileReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *MoveFileReqBody) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *MoveFileReqBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *MoveFileReqBody) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *MoveFileReqBody) GetParentFolderId() string {
	if x != nil && x.ParentFolderId != nil {
		return *x.ParentFolderId
	}
	return ""
}

func (x *MoveFileReqBody) GetDestFolderId() string {
	if x != nil && x.DestFolderId != nil {
		return *x.DestFolderId
	}
	return ""
}

func (x *MoveFileReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *MoveFileRspBody) GetRetCode() int32 {
	if x != nil && x.RetCode != nil {
		return *x.RetCode
	}
	return 0
}

func (x *MoveFileRspBody) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *MoveFileRspBody) GetClientWording() string {
	if x != nil && x.ClientWording != nil {
		return *x.ClientWording
	}
	return ""
}

func (x *MoveFileRspBody) GetParentFolderId() string {
	if x != nil && x.ParentFolderId != nil {
		return *x.ParentFolderId
	}
	return ""
}

func (x *MoveFileRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *RenameFileReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *RenameFileReqBody) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *RenameFileReqBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *RenameFileReqBody) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *RenameFileReqBody) GetParentFolderId() string {
	if x != nil && x.ParentFolderId != nil {
		return *x.ParentFolderId
	}
	return ""
}

func (x *RenameFileReqBody) GetNewFileName() string {
	if x != nil && x.NewFileName != nil {
		return *x.NewFileName
	}
	return ""
}

func (x *RenameFileReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *RenameFileRspBody) GetRetCode() int32 {
	if x != nil && x.RetCode != nil {
		return *x.RetCode
	}
	return 0
}

func (x *RenameFileRspBody) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *RenameFileRspBody) GetClientWording() string {
	if x != nil && x.ClientWording != nil {
		return *x.ClientWording
	}
	return ""
}

func (x *RenameFileRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *ReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *ResendReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *ResendReqBody) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *ResendReqBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *ResendReqBody) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *ResendReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *ResendRspBody) GetRetCode() int32 {
	if x != nil && x.RetCode != nil {
		return *x.RetCode
	}
	return 0
}

func (x *ResendRspBody) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *ResendRspBody) GetClientWording() string {
	if x != nil && x.ClientWording != nil {
		return *x.ClientWording
	}
	return ""
}

func (x *ResendRspBody) GetUploadIp() string {
	if x != nil && x.UploadIp != nil {
		return *x.UploadIp
	}
	return ""
}

func (x *ResendRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *RspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *UploadFileReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *UploadFileReqBody) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *UploadFileReqBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *UploadFileReqBody) GetEntrance() uint32 {
	if x != nil && x.Entrance != nil {
		return *x.Entrance
	}
	return 0
}

func (x *UploadFileReqBody) GetParentFolderId() string {
	if x != nil && x.ParentFolderId != nil {
		return *x.ParentFolderId
	}
	return ""
}

func (x *UploadFileReqBody) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *UploadFileReqBody) GetLocalPath() string {
	if x != nil && x.LocalPath != nil {
		return *x.LocalPath
	}
	return ""
}

func (x *UploadFileReqBody) GetFileSize() uint64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *UploadFileReqBody) GetSupportMultiUpload() bool {
	if x != nil && x.SupportMultiUpload != nil {
		return *x.SupportMultiUpload
	}
	return false
}

func (x *UploadFileReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}

func (x *UploadFileRspBody) GetRetCode() int32 {
	if x != nil && x.RetCode != nil {
		return *x.RetCode
	}
	return 0
}

func (x *UploadFileRspBody) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *UploadFileRspBody) GetClientWording() string {
	if x != nil && x.ClientWording != nil {
		return *x.ClientWording
	}
	return ""
}

func (x *UploadFileRspBody) GetUploadIp() string {
	if x != nil && x.UploadIp != nil {
		return *x.UploadIp
	}
	return ""
}

func (x *UploadFileRspBody) GetServerDns() string {
	if x != nil && x.ServerDns != nil {
		return *x.ServerDns
	}
	return ""
}

func (x *UploadFileRspBody) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *UploadFileRspBody) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *UploadFileRspBody) GetFileExist() bool {
	if x != nil && x.FileExist != nil {
		return *x.FileExist
	}
	return false
}

func (x *UploadFileRspBody) GetUploadPort() uint32 {
	if x != nil && x.UploadPort != nil {
		return *x.UploadPort
	}
	return 0
}

func (x *UploadFileRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil pointer error")
	}
	return protobuf.Encode(x)
}
