// Code generated by yaprotoc. DO NOT EDIT.
// source: oidb\0xeac.proto

package oidb0xeac

import (
	"github.com/pkg/errors"
	"github.com/segmentio/encoding/proto"
)

type ArkMsg struct {
	AppName *string `protobuf:"bytes,1,opt"`
	Json    *string `protobuf:"bytes,2,opt"`
}

func (x *ArkMsg) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *ArkMsg) GetJson() string {
	if x != nil && x.Json != nil {
		return *x.Json
	}
	return ""
}

func (x *ArkMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type BatchReqBody struct {
	GroupCode *uint64    `protobuf:"varint,1,opt"`
	Msgs      []*MsgInfo `protobuf:"bytes,2,rep"`
}

func (x *BatchReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *BatchReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type BatchRspBody struct {
	Wording    *string           `protobuf:"bytes,1,opt"`
	ErrorCode  *uint32           `protobuf:"varint,2,opt"`
	SuccCnt    *int32            `protobuf:"varint,3,opt"`
	ProcInfos  []*MsgProcessInfo `protobuf:"bytes,4,rep"`
	DigestTime *uint32           `protobuf:"varint,5,opt"`
}

func (x *BatchRspBody) GetWording() string {
	if x != nil && x.Wording != nil {
		return *x.Wording
	}
	return ""
}

func (x *BatchRspBody) GetErrorCode() uint32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

func (x *BatchRspBody) GetSuccCnt() int32 {
	if x != nil && x.SuccCnt != nil {
		return *x.SuccCnt
	}
	return 0
}

func (x *BatchRspBody) GetDigestTime() uint32 {
	if x != nil && x.DigestTime != nil {
		return *x.DigestTime
	}
	return 0
}

func (x *BatchRspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type DigestMsg struct {
	GroupCode     *uint64    `protobuf:"varint,1,opt"`
	Seq           *uint32    `protobuf:"varint,2,opt"`
	Random        *uint32    `protobuf:"varint,3,opt"`
	Content       []*MsgElem `protobuf:"bytes,4,rep"`
	TextSize      *uint64    `protobuf:"varint,5,opt"`
	PicSize       *uint64    `protobuf:"varint,6,opt"`
	VideoSize     *uint64    `protobuf:"varint,7,opt"`
	SenderUin     *uint64    `protobuf:"varint,8,opt"`
	SenderTime    *uint32    `protobuf:"varint,9,opt"`
	AddDigestUin  *uint64    `protobuf:"varint,10,opt"`
	AddDigestTime *uint32    `protobuf:"varint,11,opt"`
	StartTime     *uint32    `protobuf:"varint,12,opt"`
	LatestMsgSeq  *uint32    `protobuf:"varint,13,opt"`
	OpType        *uint32    `protobuf:"varint,14,opt"`
}

func (x *DigestMsg) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *DigestMsg) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *DigestMsg) GetRandom() uint32 {
	if x != nil && x.Random != nil {
		return *x.Random
	}
	return 0
}

func (x *DigestMsg) GetTextSize() uint64 {
	if x != nil && x.TextSize != nil {
		return *x.TextSize
	}
	return 0
}

func (x *DigestMsg) GetPicSize() uint64 {
	if x != nil && x.PicSize != nil {
		return *x.PicSize
	}
	return 0
}

func (x *DigestMsg) GetVideoSize() uint64 {
	if x != nil && x.VideoSize != nil {
		return *x.VideoSize
	}
	return 0
}

func (x *DigestMsg) GetSenderUin() uint64 {
	if x != nil && x.SenderUin != nil {
		return *x.SenderUin
	}
	return 0
}

func (x *DigestMsg) GetSenderTime() uint32 {
	if x != nil && x.SenderTime != nil {
		return *x.SenderTime
	}
	return 0
}

func (x *DigestMsg) GetAddDigestUin() uint64 {
	if x != nil && x.AddDigestUin != nil {
		return *x.AddDigestUin
	}
	return 0
}

func (x *DigestMsg) GetAddDigestTime() uint32 {
	if x != nil && x.AddDigestTime != nil {
		return *x.AddDigestTime
	}
	return 0
}

func (x *DigestMsg) GetStartTime() uint32 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *DigestMsg) GetLatestMsgSeq() uint32 {
	if x != nil && x.LatestMsgSeq != nil {
		return *x.LatestMsgSeq
	}
	return 0
}

func (x *DigestMsg) GetOpType() uint32 {
	if x != nil && x.OpType != nil {
		return *x.OpType
	}
	return 0
}

func (x *DigestMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type FaceMsg struct {
	Index *uint32 `protobuf:"varint,1,opt"`
	Text  *string `protobuf:"bytes,2,opt"`
}

func (x *FaceMsg) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *FaceMsg) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *FaceMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type GroupFileMsg struct {
	FileName []byte  `protobuf:"bytes,1,opt"`
	BusId    *uint32 `protobuf:"varint,2,opt"`
	FileId   *string `protobuf:"bytes,3,opt"`
	FileSize *uint64 `protobuf:"varint,4,opt"`
	DeadTime *uint64 `protobuf:"varint,5,opt"`
	FileSha1 []byte  `protobuf:"bytes,6,opt"`
	Ext      []byte  `protobuf:"bytes,7,opt"`
	FileMd5  []byte  `protobuf:"bytes,8,opt"`
}

func (x *GroupFileMsg) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *GroupFileMsg) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *GroupFileMsg) GetFileSize() uint64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *GroupFileMsg) GetDeadTime() uint64 {
	if x != nil && x.DeadTime != nil {
		return *x.DeadTime
	}
	return 0
}

func (x *GroupFileMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ImageMsg struct {
	Md5         *string `protobuf:"bytes,1,opt"`
	Uuid        *string `protobuf:"bytes,2,opt"`
	ImgType     *uint32 `protobuf:"varint,3,opt"`
	FileSize    *uint32 `protobuf:"varint,4,opt"`
	Width       *uint32 `protobuf:"varint,5,opt"`
	Height      *uint32 `protobuf:"varint,6,opt"`
	FileId      *uint32 `protobuf:"varint,101,opt"`
	ServerIp    *uint32 `protobuf:"varint,102,opt"`
	ServerPort  *uint32 `protobuf:"varint,103,opt"`
	FilePath    *string `protobuf:"bytes,104,opt"`
	ThumbUrl    *string `protobuf:"bytes,201,opt"`
	OriginalUrl *string `protobuf:"bytes,202,opt"`
	ResaveUrl   *string `protobuf:"bytes,203,opt"`
}

func (x *ImageMsg) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

func (x *ImageMsg) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *ImageMsg) GetImgType() uint32 {
	if x != nil && x.ImgType != nil {
		return *x.ImgType
	}
	return 0
}

func (x *ImageMsg) GetFileSize() uint32 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *ImageMsg) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *ImageMsg) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *ImageMsg) GetFileId() uint32 {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return 0
}

func (x *ImageMsg) GetServerIp() uint32 {
	if x != nil && x.ServerIp != nil {
		return *x.ServerIp
	}
	return 0
}

func (x *ImageMsg) GetServerPort() uint32 {
	if x != nil && x.ServerPort != nil {
		return *x.ServerPort
	}
	return 0
}

func (x *ImageMsg) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *ImageMsg) GetThumbUrl() string {
	if x != nil && x.ThumbUrl != nil {
		return *x.ThumbUrl
	}
	return ""
}

func (x *ImageMsg) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

func (x *ImageMsg) GetResaveUrl() string {
	if x != nil && x.ResaveUrl != nil {
		return *x.ResaveUrl
	}
	return ""
}

func (x *ImageMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type MsgElem struct {
	Type         *uint32       `protobuf:"varint,1,opt"`
	TextMsg      *TextMsg      `protobuf:"bytes,11,opt"`
	FaceMsg      *FaceMsg      `protobuf:"bytes,12,opt"`
	ImageMsg     *ImageMsg     `protobuf:"bytes,13,opt"`
	GroupFileMsg *GroupFileMsg `protobuf:"bytes,14,opt"`
	ShareMsg     *ShareMsg     `protobuf:"bytes,15,opt"`
	RichMsg      *RichMsg      `protobuf:"bytes,16,opt"`
	ArkMsg       *ArkMsg       `protobuf:"bytes,17,opt"`
}

func (x *MsgElem) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *MsgElem) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type MsgInfo struct {
	Seq    *uint32 `protobuf:"varint,1,opt"`
	Random *uint32 `protobuf:"varint,2,opt"`
}

func (x *MsgInfo) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *MsgInfo) GetRandom() uint32 {
	if x != nil && x.Random != nil {
		return *x.Random
	}
	return 0
}

func (x *MsgInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type MsgProcessInfo struct {
	Msg        *MsgInfo `protobuf:"bytes,1,opt"`
	ErrorCode  *uint32  `protobuf:"varint,2,opt"`
	DigestUin  *uint64  `protobuf:"varint,3,opt"`
	DigestTime *uint32  `protobuf:"varint,4,opt"`
}

func (x *MsgProcessInfo) GetErrorCode() uint32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

func (x *MsgProcessInfo) GetDigestUin() uint64 {
	if x != nil && x.DigestUin != nil {
		return *x.DigestUin
	}
	return 0
}

func (x *MsgProcessInfo) GetDigestTime() uint32 {
	if x != nil && x.DigestTime != nil {
		return *x.DigestTime
	}
	return 0
}

func (x *MsgProcessInfo) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ReqBody struct {
	GroupCode *uint64 `protobuf:"varint,1,opt"`
	Seq       *uint32 `protobuf:"varint,2,opt"`
	Random    *uint32 `protobuf:"varint,3,opt"`
}

func (x *ReqBody) GetGroupCode() uint64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

func (x *ReqBody) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *ReqBody) GetRandom() uint32 {
	if x != nil && x.Random != nil {
		return *x.Random
	}
	return 0
}

func (x *ReqBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type RichMsg struct {
	ServiceId    *uint32 `protobuf:"varint,1,opt"`
	Xml          *string `protobuf:"bytes,2,opt"`
	LongMsgResid *string `protobuf:"bytes,3,opt"`
}

func (x *RichMsg) GetServiceId() uint32 {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return 0
}

func (x *RichMsg) GetXml() string {
	if x != nil && x.Xml != nil {
		return *x.Xml
	}
	return ""
}

func (x *RichMsg) GetLongMsgResid() string {
	if x != nil && x.LongMsgResid != nil {
		return *x.LongMsgResid
	}
	return ""
}

func (x *RichMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type RspBody struct {
	Wording    *string    `protobuf:"bytes,1,opt"`
	DigestUin  *uint64    `protobuf:"varint,2,opt"`
	DigestTime *uint32    `protobuf:"varint,3,opt"`
	Msg        *DigestMsg `protobuf:"bytes,4,opt"`
	ErrorCode  *uint32    `protobuf:"varint,10,opt"`
}

func (x *RspBody) GetWording() string {
	if x != nil && x.Wording != nil {
		return *x.Wording
	}
	return ""
}

func (x *RspBody) GetDigestUin() uint64 {
	if x != nil && x.DigestUin != nil {
		return *x.DigestUin
	}
	return 0
}

func (x *RspBody) GetDigestTime() uint32 {
	if x != nil && x.DigestTime != nil {
		return *x.DigestTime
	}
	return 0
}

func (x *RspBody) GetErrorCode() uint32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

func (x *RspBody) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type ShareMsg struct {
	Type       *string `protobuf:"bytes,1,opt"`
	Title      *string `protobuf:"bytes,2,opt"`
	Summary    *string `protobuf:"bytes,3,opt"`
	Brief      *string `protobuf:"bytes,4,opt"`
	Url        *string `protobuf:"bytes,5,opt"`
	PictureUrl *string `protobuf:"bytes,6,opt"`
	Action     *string `protobuf:"bytes,7,opt"`
	Source     *string `protobuf:"bytes,8,opt"`
	SourceUrl  *string `protobuf:"bytes,9,opt"`
}

func (x *ShareMsg) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ShareMsg) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ShareMsg) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *ShareMsg) GetBrief() string {
	if x != nil && x.Brief != nil {
		return *x.Brief
	}
	return ""
}

func (x *ShareMsg) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ShareMsg) GetPictureUrl() string {
	if x != nil && x.PictureUrl != nil {
		return *x.PictureUrl
	}
	return ""
}

func (x *ShareMsg) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *ShareMsg) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ShareMsg) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

func (x *ShareMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}

type TextMsg struct {
	Str []byte `protobuf:"bytes,1,opt"`
}

func (x *TextMsg) Marshal() ([]byte, error) {
	if x == nil {
		return nil, errors.New("nil message")
	}
	return proto.Marshal(x)
}
