// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/faceroam/faceroam.proto

package faceroam

type PlatInfo struct {
	Implat *int64  `protobuf:"varint,1,opt"`
	Osver  *string `protobuf:"bytes,2,opt"`
	Mqqver *string `protobuf:"bytes,3,opt"`
}

func (x *PlatInfo) GetImplat() int64 {
	if x != nil && x.Implat != nil {
		return *x.Implat
	}
	return 0
}

func (x *PlatInfo) GetOsver() string {
	if x != nil && x.Osver != nil {
		return *x.Osver
	}
	return ""
}

func (x *PlatInfo) GetMqqver() string {
	if x != nil && x.Mqqver != nil {
		return *x.Mqqver
	}
	return ""
}

type FaceroamReqBody struct {
	Comm          *PlatInfo      `protobuf:"bytes,1,opt"`
	Uin           *uint64        `protobuf:"varint,2,opt"`
	SubCmd        *uint32        `protobuf:"varint,3,opt"`
	ReqUserInfo   *ReqUserInfo   `protobuf:"bytes,4,opt"`
	ReqDeleteItem *ReqDeleteItem `protobuf:"bytes,5,opt"`
}

func (x *FaceroamReqBody) GetUin() uint64 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *FaceroamReqBody) GetSubCmd() uint32 {
	if x != nil && x.SubCmd != nil {
		return *x.SubCmd
	}
	return 0
}

type ReqDeleteItem struct {
	Filename []string `protobuf:"bytes,1,rep"`
}

type ReqUserInfo struct {
}

type FaceroamRspBody struct {
	Ret           *int64         `protobuf:"varint,1,opt"`
	Errmsg        *string        `protobuf:"bytes,2,opt"`
	SubCmd        *uint32        `protobuf:"varint,3,opt"`
	RspUserInfo   *RspUserInfo   `protobuf:"bytes,4,opt"`
	RspDeleteItem *RspDeleteItem `protobuf:"bytes,5,opt"`
}

func (x *FaceroamRspBody) GetRet() int64 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *FaceroamRspBody) GetErrmsg() string {
	if x != nil && x.Errmsg != nil {
		return *x.Errmsg
	}
	return ""
}

func (x *FaceroamRspBody) GetSubCmd() uint32 {
	if x != nil && x.SubCmd != nil {
		return *x.SubCmd
	}
	return 0
}

type RspDeleteItem struct {
	Filename []string `protobuf:"bytes,1,rep"`
	Ret      []int64  `protobuf:"varint,2,rep"`
}

type RspUserInfo struct {
	Filename    []string `protobuf:"bytes,1,rep"`
	DeleteFile  []string `protobuf:"bytes,2,rep"`
	Bid         *string  `protobuf:"bytes,3,opt"`
	MaxRoamSize *uint32  `protobuf:"varint,4,opt"`
	EmojiType   []uint32 `protobuf:"varint,5,rep"`
}

func (x *RspUserInfo) GetBid() string {
	if x != nil && x.Bid != nil {
		return *x.Bid
	}
	return ""
}

func (x *RspUserInfo) GetMaxRoamSize() uint32 {
	if x != nil && x.MaxRoamSize != nil {
		return *x.MaxRoamSize
	}
	return 0
}
