// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: oidb0xe07.proto

package oidb

type DE07ReqBody struct {
	Version    int32       `protobuf:"varint,1,opt"`
	Client     int32       `protobuf:"varint,2,opt"`
	Entrance   int32       `protobuf:"varint,3,opt"`
	OcrReqBody *OCRReqBody `protobuf:"bytes,10,opt"`
}

func (x *DE07ReqBody) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DE07ReqBody) GetClient() int32 {
	if x != nil {
		return x.Client
	}
	return 0
}

func (x *DE07ReqBody) GetEntrance() int32 {
	if x != nil {
		return x.Entrance
	}
	return 0
}

func (x *DE07ReqBody) GetOcrReqBody() *OCRReqBody {
	if x != nil {
		return x.OcrReqBody
	}
	return nil
}

type OCRReqBody struct {
	ImageUrl              string `protobuf:"bytes,1,opt"`
	LanguageType          string `protobuf:"bytes,2,opt"`
	Scene                 string `protobuf:"bytes,3,opt"`
	OriginMd5             string `protobuf:"bytes,10,opt"`
	AfterCompressMd5      string `protobuf:"bytes,11,opt"`
	AfterCompressFileSize int32  `protobuf:"varint,12,opt"`
	AfterCompressWeight   int32  `protobuf:"varint,13,opt"`
	AfterCompressHeight   int32  `protobuf:"varint,14,opt"`
	IsCut                 bool   `protobuf:"varint,15,opt"`
}

func (x *OCRReqBody) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *OCRReqBody) GetLanguageType() string {
	if x != nil {
		return x.LanguageType
	}
	return ""
}

func (x *OCRReqBody) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *OCRReqBody) GetOriginMd5() string {
	if x != nil {
		return x.OriginMd5
	}
	return ""
}

func (x *OCRReqBody) GetAfterCompressMd5() string {
	if x != nil {
		return x.AfterCompressMd5
	}
	return ""
}

func (x *OCRReqBody) GetAfterCompressFileSize() int32 {
	if x != nil {
		return x.AfterCompressFileSize
	}
	return 0
}

func (x *OCRReqBody) GetAfterCompressWeight() int32 {
	if x != nil {
		return x.AfterCompressWeight
	}
	return 0
}

func (x *OCRReqBody) GetAfterCompressHeight() int32 {
	if x != nil {
		return x.AfterCompressHeight
	}
	return 0
}

func (x *OCRReqBody) GetIsCut() bool {
	if x != nil {
		return x.IsCut
	}
	return false
}

type DE07RspBody struct {
	RetCode    int32       `protobuf:"varint,1,opt"`
	ErrMsg     string      `protobuf:"bytes,2,opt"`
	Wording    string      `protobuf:"bytes,3,opt"`
	OcrRspBody *OCRRspBody `protobuf:"bytes,10,opt"`
}

func (x *DE07RspBody) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *DE07RspBody) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *DE07RspBody) GetWording() string {
	if x != nil {
		return x.Wording
	}
	return ""
}

func (x *DE07RspBody) GetOcrRspBody() *OCRRspBody {
	if x != nil {
		return x.OcrRspBody
	}
	return nil
}

type TextDetection struct {
	DetectedText string   `protobuf:"bytes,1,opt"`
	Confidence   int32    `protobuf:"varint,2,opt"`
	Polygon      *Polygon `protobuf:"bytes,3,opt"`
	AdvancedInfo string   `protobuf:"bytes,4,opt"`
}

func (x *TextDetection) GetDetectedText() string {
	if x != nil {
		return x.DetectedText
	}
	return ""
}

func (x *TextDetection) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TextDetection) GetPolygon() *Polygon {
	if x != nil {
		return x.Polygon
	}
	return nil
}

func (x *TextDetection) GetAdvancedInfo() string {
	if x != nil {
		return x.AdvancedInfo
	}
	return ""
}

type Polygon struct {
	Coordinates []*Coordinate `protobuf:"bytes,1,rep"`
}

func (x *Polygon) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Coordinate struct {
	X int32 `protobuf:"varint,1,opt"`
	Y int32 `protobuf:"varint,2,opt"`
}

func (x *Coordinate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Language struct {
	Language     string `protobuf:"bytes,1,opt"`
	LanguageDesc string `protobuf:"bytes,2,opt"`
}

func (x *Language) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Language) GetLanguageDesc() string {
	if x != nil {
		return x.LanguageDesc
	}
	return ""
}

type OCRRspBody struct {
	TextDetections           []*TextDetection `protobuf:"bytes,1,rep"`
	Language                 string           `protobuf:"bytes,2,opt"`
	RequestId                string           `protobuf:"bytes,3,opt"`
	OcrLanguageList          []string         `protobuf:"bytes,101,rep"`
	DstTranslateLanguageList []string         `protobuf:"bytes,102,rep"`
	LanguageList             []*Language      `protobuf:"bytes,103,rep"`
	AfterCompressWeight      int32            `protobuf:"varint,111,opt"`
	AfterCompressHeight      int32            `protobuf:"varint,112,opt"`
}

func (x *OCRRspBody) GetTextDetections() []*TextDetection {
	if x != nil {
		return x.TextDetections
	}
	return nil
}

func (x *OCRRspBody) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *OCRRspBody) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OCRRspBody) GetOcrLanguageList() []string {
	if x != nil {
		return x.OcrLanguageList
	}
	return nil
}

func (x *OCRRspBody) GetDstTranslateLanguageList() []string {
	if x != nil {
		return x.DstTranslateLanguageList
	}
	return nil
}

func (x *OCRRspBody) GetLanguageList() []*Language {
	if x != nil {
		return x.LanguageList
	}
	return nil
}

func (x *OCRRspBody) GetAfterCompressWeight() int32 {
	if x != nil {
		return x.AfterCompressWeight
	}
	return 0
}

func (x *OCRRspBody) GetAfterCompressHeight() int32 {
	if x != nil {
		return x.AfterCompressHeight
	}
	return 0
}
